name: Tarea Github Actions
on: pull_request

jobs:
  log_greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Environment setting
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_SHA }}
    - name: Log greeting and PR details
      uses: actions/checkout@v3
      run: |
         PR_AUTHOR="${{ github.event.pull_request.user.login }}";

         # Log info
         chmod +x ./Tareas/IS727272\ -\ Github\ Actions.sh;
         ./Tareas/IS727272\ -\ Github\ Actions.sh | tee ./logs/PR_log.txt;
      shell: bash

