name: Tarea Github Actions
on: pull_request

jobs:
  log_greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log greeting and PR details
      run: |
         # Definición de variables
         PR_AUTHOR="${{ github.event.pull_request.user.login }}";
         PR_COMMIT="${{ github.event.head_commit.message }}";

         # Log info
         chmod +x ./Tareas/IS727272\ -\ Github\ Actions.sh;
         ./Tareas/IS727272\ -\ Github\ Actions.sh | tee ./logs/PR_log.txt;
      shell: bash

