name: Tarea Github Actions
on: pull_request

jobs:
  log_greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log greeting and PR details
      with:
        ref: ${{ env.GITHUB_SHA }}
      run: |
         PR_AUTHOR="${{ github.event.pull_request.user.login }}";

         # Log info
         chmod +x ./Tareas/IS727272\ -\ Github\ Actions.sh;
         ./Tareas/IS727272\ -\ Github\ Actions.sh | tee ./logs/PR_log.txt;
      shell: bash

